### ISSUE TITLE
Unterbrechung der Seriellen (USB) COM Verbindung - wie erkennen?

### ISSUE THREAD

**Issue by stevstrong** [Erlkoenig90/f1usb#2]
Hallo Niklas,
ich hab mittlereweile geschafft das program nach meiner bedürfnisse anzupassen (USART komplet auf IRQ umzustellen ohne DMA, mit nur einer VCP schnittstelle), auch habe ich paar optimierungen beim daten kopieren (EPBuffer::transmitPacket, EPBuffer::getReceivedData) implementiert.
Jetzt wollte ich fragen wie kann mann auf VCP ebene feststellen dass der host die USB serielle verbindung abgetrennt hat. also nicht kabel weg sondern nur USB serial disconnect. ich möchte detektieren wenn z.b die serielle applikation aufm PC abstürtzt oder zugemacht wird.
kannst du mir bitte hier weiterhelfen? bin für jeden hinweis dankbar.
vielen dank im voraus.

**Comment by Erlkoenig90** [comment]
> USART komplet auf IRQ umzustellen ohne DMA

Das ist aber ziemlich ineffizient...

> Jetzt wollte ich fragen wie kann mann auf VCP ebene feststellen dass der host die USB serielle verbindung abgetrennt hat. also nicht kabel weg sondern nur USB serial disconnect.

Das geht nicht wirklich. Der Host sendet dem Device keinerlei Information darüber. Über eine normale serielle Schnittstelle lässt sich das ja auch nicht feststellen. Die Anwendung muss dem Gerät das Beenden mitteilen...

**Comment by stevstrong** [comment]
> Das ist aber ziemlich ineffizient...

na ja, nicht ganz, ich verwende einen 2kb großen ring-puffer, und das schreiben-lesen passiert sehr schnell in der USART ISR

> Das geht nicht wirklich. Der Host sendet dem Device keinerlei Information darüber. Über eine normale serielle Schnittstelle lässt sich das ja auch nicht feststellen. Die Anwendung muss dem Gerät das Beenden mitteilen...

danke, das hab ich leider irgendwie vermutet :(

**Comment by Erlkoenig90** [comment]
> na ja, nicht ganz, ich verwende einen 2kb großen ring-puffer, und das schreiben-lesen passiert sehr schnell in der USART ISR

Dennoch muss für jedes einzelne Byte die ISR aufgerufen werden, mit Register-Sichern und allem. Das sind mindestens ca. 20 Takte pro Byte. Bei DMA entfällt das. Das geht auch mit Ringpuffern.

> danke, das hab ich leider irgendwie vermutet :(

Die korrekte Lösung wäre die Implementation eines eigenen USB-Protokolls statt CDC, und einen Kernel-Treiber programmieren welcher das Beenden des Programms erkennt und das dem Gerät mitteilt. Das hat aber auch seine eigenen Probleme.

**Comment by stevstrong** [comment]
> Dennoch muss für jedes einzelne Byte die ISR aufgerufen werden, mit Register-Sichern und allem. 
Das sind mindestens ca. 20 Takte pro Byte. Bei DMA entfällt das. Das geht auch mit Ringpuffern.

das stimmt natürlich, allerdings ist der STM32 ein biest, der schafft das locker. und ich benutze DMA für was anderes und das hätte zu konflikt geführt ;)

> Die korrekte Lösung wäre die Implementation eines eigenen USB-Protokolls statt CDC, und einen Kernel-Treiber programmieren welcher das Beenden des Programms erkennt und das dem Gerät mitteilt. Das hat aber auch seine eigenen Probleme.

ich hab auf etwas ähnliches gedacht, also eine andere serielle anwendung die auf die gleiche USB COM port zugreifen möchte, und versucht solange bis der eine weg ist... und wenn der es schafft, dann werden die funktionen VCP::setLineCoding() und VCP::confUsart() aufgerufen, oder? sogar zwei mal, für beide IN und OUT ep.
